### ISSUE TITLE
[Request] Are you planning to add the discover option ?

### ISSUE THREAD

**Issue by Sykairos** [Superjo149/auryo#65] opened 2017-12-12 13:13 UTC
Hello!
First i would like to thank you for the good job!
I was wondering, if you were planning to add the discover option available on soundcloud that allow you to find new sounds based on the sounds you liked or similar to a sound you liked (Not the Stream, but the discover section).
Keep up the good work.
Sykairos

**Comment by Superjo149** [comment] 2018-12-13 18:56
Duplicate of #154

**Closed by Superjo149** 2018-12-13 18:56 UTC
Labels: ✌️ duplicate
