### ISSUE TITLE
"For you" section spam.

### ISSUE THREAD

**Issue by Darky2018** [Superjo149/auryo#232] opened 2019-12-01 12:08 UTC
When i click on "For you" section on my linux system it starts spamming "Something went wrong".

**Comment by b0wter** [comment] 2019-12-04 08:38
Same for me. Here is the output of the about dialog:

![image](https://user-images.githubusercontent.com/614261/70126671-ce868e00-1679-11ea-9a0e-3c76dfa5143e.png)

**Comment by CNOT** [comment] 2019-12-09 21:45
Duplicate of #221

**Comment by Superjo149** [comment] 2020-01-23 20:48
Closed as this is a duplicate. Please go to #221 to follow up.

**Closed by Superjo149** 2020-01-23 20:48 UTC
