### ISSUE TITLE
This track is not streamable

### ISSUE THREAD

**Issue by james-munson** [Superjo149/auryo#158] opened 2018-11-23 23:08 UTC
some tracks say This track is not streamable?

**Comment by Secr3ts** [comment] 2018-12-01 12:15
Have the same issue... In my favorite list.
Here's a pic from it:
![auryoissue](https://user-images.githubusercontent.com/42939294/49328104-fcb72680-f56a-11e8-915e-63e75d56b0be.png)
(if you dont see anything, look at the first track (Dex Atson - Immunity) you should normally see a white circle right? that's the bug.. i can't stream certain tracks.

**Comment by formatme** [comment] 2018-12-04 07:13
ya, i dont think i had this issue when i first started using auyro

**Comment by LiveNL** [comment] 2018-12-04 07:31
Adding a track to the queue will make it possible to play one, but that's just a quick fix.

**Comment by Superjo149** [comment] 2018-12-05 08:14
This is definitly a bug, will look at it this evening.

**Comment by Secr3ts** [comment] 2018-12-08 10:45
This is not fixed i think. for reproducing (i'm not sure it'll work) go to charts and select Dubstep

**Comment by Superjo149** [comment] 2018-12-08 11:02
Maybe it's a country thing? When I search the track "immunity", I am able to play It no problem. Are you able to play this on SoundCloud itself?

**Comment by formatme** [comment] 2018-12-09 03:08
yes

**Comment by LiveNL** [comment] 2018-12-10 07:56
The issue isn't gone for me either. So far I haven't found any logic about which tracks are unplayable (without adding them to the queue). Besides that, I found that some tracks aren't shown at all (in comparison with my stream on the soundcloud website), and that every track is shown as a repost (some from the artist themselves although they are the original poster at that point). If I can provide you with more data, let me know.

**Comment by Secr3ts** [comment] 2018-12-10 20:36
@Superjo149  yes i'm able to play it in soundcloud itself. (Also thanks losting time to fix that :D )
![screenshot 30](https://user-images.githubusercontent.com/42939294/49760007-a1500b80-fcc3-11e8-9934-818eefbdad07.png)

**Comment by Superjo149** [comment] 2018-12-12 07:14
I may know whats causing this, will look at it this evening. I'm sorry, I'm a bit busy.

**Comment by Superjo149** [comment] 2018-12-12 17:22
@LiveNL Some tracks are not visible on Auryo because SoundCloud doesn't let third party apps access all music. It's a different issue which cannot be fixed.

**Comment by LiveNL** [comment] 2018-12-13 07:04
Thanks @Superjo149 , too bad it seems to be an issue for quite a few of them (for me).

**Comment by Superjo149** [comment] 2018-12-13 22:01
This issue is possibly resolved in 2.3.0 . Please note that some tracks may show this still and could in fact not be streamable via a third party app. If you think a track is wrongfully marked "not streamable". You can check this by adding it to your queue and seeing if it plays.

**Comment by Superjo149** [comment] 2018-12-15 09:58
@james-munson @Secr3ts @formatme @LiveNL Can someone please verify if this issue has been resolved?

**Closed** 2018-12-15 20:45 UTC
Labels: 🐛bug

**Comment by LiveNL** [comment] 2018-12-17 08:09
Same for me, seems to be fixed 👍 thanks

**Comment by Secr3ts** [comment] 2018-12-20 19:21
Thanks again @Superjo149 ! It works very well

**Comment by Superjo149** [comment] 2018-12-20 19:22
Ofcourse, no problem 😉

**Comment by Secr3ts** [comment] 2018-12-20 19:48
but can you "teach" me how Auryo works? i really want to help ! 🙏

**Comment by Superjo149** [comment] 2018-12-20 19:59
I can use all the help I can get, I would love to add more features. 💪 But it takes time.  I won't be able to teach you, but I will be able to guide you. Please join https://gitter.im/auryoapp-/Lobby and PM me there. 😀
