### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by bennybenjaman** [Superjo149/auryo#231] opened 2019-11-27 06:52 UTC
# 💡 Feature request

## What do you propose

A dark theme
## Whats steps can we take to implement it

Add a dark theme
## Examples

Dark theme

**Comment by BlobCodes** [comment] 2019-11-28 14:04
Duplicate of #97 
You can close this, it's out on the next release.

**Comment by bennybenjaman** [comment] 2019-12-03 15:57
Nice

**Closed** 2019-12-03 15:57 UTC
