### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by ScorpionVM** [Superjo149/auryo#222] opened 2019-09-20 12:10 UTC
# 🐛 Bug report

## What issue are you facing
When I started application Auryo, i get error " 'indexOf' of null "
![image](https://user-images.githubusercontent.com/41546258/65325758-6109ac00-dbb8-11e9-93f1-c6ae84c00397.png)
Then i run application from terminal to view cause of errors. The error is: "MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit"
![image](https://user-images.githubusercontent.com/41546258/65325595-fc4e5180-dbb7-11e9-8bf9-be30498286bf.png)

## Steps to reproduce
Run Auryo from terminal:

/usr/local/bin/auryo

#### Which Operating System? 
OS: Linux Mint 19.1 Cinnamon

#### Which version of Auryo? 
Version of app: 2.4.0

**Comment by Superjo149** [comment] 2020-01-23 20:49
Duplicate of #191

**Closed by Superjo149** 2020-01-23 20:49 UTC
