### ISSUE TITLE
The application is crashing while recording the playlist.

### ISSUE THREAD

**Issue by fatihizm** [Superjo149/auryo#58] opened 2017-11-09 12:59 UTC
It's a tight one. The application crashes when we click the save playlist option after searching and getting the desired result.

- MacOS 13.1

- 1.4.2

- When saving the playlist.

- Nothing. Quit app - re-open

I took a screen video to see the error. I added the screen capture to the zip file because the video format is not supported.

[Auryo.zip](https://github.com/Superjo149/auryo/files/1457631/Auryo.zip)

**Comment by Superjo149** [comment] 2018-08-26 10:04
Could you check if this is still happening in v2? I'm unable to reproduce this.

**Comment by Superjo149** [comment] 2018-11-03 08:41
I assume this is fixed, closing this issue.

**Closed by Superjo149** 2018-11-03 08:41 UTC
